import Head from "next/head";
import Image from "next/image";
import Feed from "../components/feed/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import styles from "../styles/Home.module.css";

export default function Home({ newsResults, randomUsersResults }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-[88rem] mx-auto">
        {/** Sidebar */}
        <Sidebar />
        {/** Main/Feed */}
        <Feed />
        {/** Widget */}
        <Widgets
          newsResults={newsResults.articles}
          randomUsersResults={randomUsersResults.results}
        />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/science/us.json"
  )
    .then((res) => res.json())
    .catch((err) => log(err)); // error without catch err

  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  )
    .then((res) => res.json())
    .catch((err) => log(err));

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}
